### ISSUE TITLE
Can't figure out the usage format

### ISSUE THREAD

**Issue by noembryo** [Fish-Git/totp#1]
Thank you for your effort!
I truly appreciate it, since I'm in the same boat and the time is ticking.. 💣 
I might be missing something obvious here, but I can't find a way to use this app.
Using Windows 10x64

I tried to test it using the initial examples in text file and feeding it to the app with
`D:\totp.exe "path2text.file"`
or one by one like `D:\totp.exe 765432ZYXWVUTSRQPONMLKJIHGFEDCBA` or 
`D:\totp.exe  sha256:ABCDEFGHIJKLMNOPQRSTUVWXYZ234567:8 adam@acme.org`
but I get no output..

Used cmd and PowerShell, with and without administrative privileges..
Any advices?

**Comment by tomek-o** [comment]
I think you need to paste arguments after starting totp from command line or pass it from file using "<" operator, e.g. totp.exe < file.txt
I'm curious myself if this works.

**Comment by tomek-o** [comment]
I think you need to paste arguments after starting totp from command line or pass it from file using "<" operator, e.g. totp.exe < file.txt
I'm curious myself if this works.

**Comment by noembryo** [comment]
> I think you need to paste arguments after starting totp from command line or pass it from file using "<" operator, e.g. totp.exe < file.txt

I don't understand what you're suggesting.
As I wrote, I already passed arguments from the command line like `D:\totp.exe  sha256:ABCDEFGHIJKLMNOPQRSTUVWXYZ234567:8 adam@acme.org` and it didn't work.
The `totp.exe < test.txt`  did not produce an output either.

>  I'm curious myself if this works.

So, for you it works? At what platform?

**Comment by tomek-o** [comment]
It generates 6 or 8 digits codes with your example inputs, I haven't tested it further yet (I haven't configured 2FA for my github account yet).
This app is not parsing command line, it reads inputs from stdin/console.
I'm just opening command line, running just "totp.exe" - and secret/line has to be either entered manually (and stdin echo is intentionally disabled) or pasted there.

Alternatively, if placing `sha256:ABCDEFGHIJKLMNOPQRSTUVWXYZ234567:8 adam@acme.org` in file.txt (for convenience in same folder as totp.exe) I'm using Windows pipe: totp.exe < file.txt
and getting output like this:

```
e:\zrzut\totp>totp < file.txt
94144552  adam@acme.org
```
Works for me on both Win7 and Win10 64-bit after copying libcrypto-3-x64.dll next to totp.exe. If it wouldn't work then missing Visual C++ Runtime(s) would be usual suspect, though Windows should show popup with missing dll name then.

**Comment by noembryo** [comment]
> Works for me on both Win7 and Win10 64-bit after copying libcrypto-3-x64.dll next to totp.exe. If it wouldn't work then missing Visual C++ Runtime(s) would be usual suspect, though Windows should show popup with missing dll name then.

What `libcrypto-3-x64.dll`? There is no mention of this anywhere!
I tried with v3.20 and 3.13 (x64) and now the totp just hangs there..
What version are you using?

Anyway, I moved on and used another [totp flavor](https://github.com/arcanericky/totp) that it just works, so everything is OK..

**Comment by tomek-o** [comment]
libcrypto-3-x64.dll is a required DLL, it can be obtained by installing Win64OpenSSL_Light-3_1_3.exe.
Inspired by this project I've made today similar, very simple GUI application, using standalone HMAC-SHA1 instead of OpenSSL:
![TotpGenerator](https://github.com/Fish-Git/totp/assets/43222462/5a08585d-e4e1-4f86-a86a-6c45638e359f)
https://github.com/tomek-o/totp-generator
So far I've tested it on my account, seems to be working.

**Comment by noembryo** [comment]
> libcrypto-3-x64.dll is a required DLL,

There is no mention of that requirement anywhere in the project instructions.
> it can be obtained by installing Win64OpenSSL_Light-3_1_3.exe.

Thanks, but no thanks..
I don't want to install more stuff on my system.
This is why I checked this project at the first place.

Well, it doesn't matter now, since I solved my problem..

**Comment by SkybuckFlying** [comment]
This tool only seems to accept keyboard press and when caps lock is on, once secret is typed in press enter.

Indeed it's a strange application.

**Comment by Fish-Git** [comment]
Hopefully, [version 1.2](https://github.com/Fish-Git/totp/releases/tag/v1.2.0) _(along with its updated associated [README](https://github.com/Fish-Git/totp/blob/master/README.md))_ will provide better information regarding how to use the program. Let me know if it doesn't and I will try to address your complaint. Thanks.

Closing.
