### ISSUE TITLE
Fails on windows 11, simply hangs, does nothing.

### ISSUE THREAD

**Issue by SkybuckFlying** [Fish-Git/totp#2]
Your tool fails massively on Windows 11, I tried it, here is a live stream:

It simply seems to hang:

https://www.youtube.com/live/hfBqzlVsUmI?si=V7UxHNL9pzovCU3e

**Comment by SkybuckFlying** [comment]
It does seem to be working, but it is weird as fuck, command line parameters not working, must use the keyboard to type in the secret and then press enter ?! Was it too much for you to document this properly ?!?!?!?!?!?!?!?!?:

https://www.youtube.com/live/MyyBbhV00rs?si=Mq4chy-ig6xJWYSa

I suspect it's done this way to make copy & paste hard ?!

By the way when trying to copy & paste into windows 11 terminal window it will reveal the contents of the text !

Don't do this on a live stream with your bitcoin private keys !

What a fucking mess !

Laterrrrrr

**Comment by SkybuckFlying** [comment]
I see a big down side to this 2FA...:

1. It's hard to remember the secret.
2. It's need special software.

So it's very "non-portable/convenient".

If I go to my laptop and went to login in there instead of my main PC where I setup it up I am screwed... and at the very least I need to "transfer" the secret and setup the software again !

It's easy to see how this can lead to leaks of secrets in case the laptop is "dumped" into the garbage.

A rememberable password is more secure in that regards... this is definetly a turn for the worse...

**Comment by SkybuckFlying** [comment]
Also some further notes:

1. Caps lock must be on for the this application to work, this should be documented somewhere.
2. Enter must be pressed to acquire the number.
3. *************** should be shown when typing.... that would help to see the application has focus and is responding to key presses.

**Comment by Fish-Git** [comment]
Hopefully, [version 1.2](https://github.com/Fish-Git/totp/releases/tag/v1.2.0) _(along with its updated associated [README](https://github.com/Fish-Git/totp/blob/master/README.md))_ will provide better information regarding how to use the program. Let me know if it doesn't and I will try to address your complaint. Thanks.
